package com.abbyy.recognitionserver3_xml.recognitionserver3_xml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-04-24T11:07:32.469+02:00
 * Generated source version: 3.1.9
 * 
 */
@WebService(targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", name = "RSSoapServiceSoap")
@XmlSeeAlso({com.abbyy.recognitionserver3_xml.recognitionserver3.ObjectFactory.class})
public interface RSSoapServiceSoap {

    @WebMethod(operationName = "ProcessTicket", action = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml/ProcessTicket")
    @RequestWrapper(localName = "ProcessTicket", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abbyy.recognitionserver3_xml.recognitionserver3.ProcessTicket")
    @ResponseWrapper(localName = "ProcessTicketResponse", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abbyy.recognitionserver3_xml.recognitionserver3.ProcessTicketResponse")
    @WebResult(name = "ProcessTicketResult", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
    public com.abbyy.recognitionserver3_xml.recognitionserver3.XmlResult processTicket(
        @WebParam(name = "location", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
        java.lang.String location,
        @WebParam(name = "workflowName", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
        java.lang.String workflowName,
        @WebParam(name = "ticket", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
        com.abbyy.recognitionserver3_xml.recognitionserver3.XmlTicket ticket
    );

    @WebMethod(operationName = "DoNothingMethod2", action = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml/DoNothingMethod2")
    @RequestWrapper(localName = "DoNothingMethod2", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abbyy.recognitionserver3_xml.recognitionserver3.DoNothingMethod2")
    @ResponseWrapper(localName = "DoNothingMethod2Response", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abbyy.recognitionserver3_xml.recognitionserver3.DoNothingMethod2Response")
    public void doNothingMethod2(
        @WebParam(name = "stub", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
        com.abbyy.recognitionserver3_xml.recognitionserver3.StubDocumentAttributesCollection stub
    );

    @WebMethod(operationName = "CreateTicket", action = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml/CreateTicket")
    @RequestWrapper(localName = "CreateTicket", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abbyy.recognitionserver3_xml.recognitionserver3.CreateTicket")
    @ResponseWrapper(localName = "CreateTicketResponse", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abbyy.recognitionserver3_xml.recognitionserver3.CreateTicketResponse")
    @WebResult(name = "CreateTicketResult", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
    public com.abbyy.recognitionserver3_xml.recognitionserver3.XmlTicket createTicket(
        @WebParam(name = "location", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
        java.lang.String location,
        @WebParam(name = "workflowName", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
        java.lang.String workflowName
    );

    @WebMethod(operationName = "ProcessFile", action = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml/ProcessFile")
    @RequestWrapper(localName = "ProcessFile", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abbyy.recognitionserver3_xml.recognitionserver3.ProcessFile")
    @ResponseWrapper(localName = "ProcessFileResponse", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abbyy.recognitionserver3_xml.recognitionserver3.ProcessFileResponse")
    @WebResult(name = "ProcessFileResult", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
    public com.abbyy.recognitionserver3_xml.recognitionserver3.XmlResult processFile(
        @WebParam(name = "location", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
        java.lang.String location,
        @WebParam(name = "workflowName", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
        java.lang.String workflowName,
        @WebParam(name = "file", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
        com.abbyy.recognitionserver3_xml.recognitionserver3.FileContainer file
    );

    @WebMethod(operationName = "DoNothingMethod", action = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml/DoNothingMethod")
    @RequestWrapper(localName = "DoNothingMethod", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abbyy.recognitionserver3_xml.recognitionserver3.DoNothingMethod")
    @ResponseWrapper(localName = "DoNothingMethodResponse", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abbyy.recognitionserver3_xml.recognitionserver3.DoNothingMethodResponse")
    public void doNothingMethod(
        @WebParam(name = "stub", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
        com.abbyy.recognitionserver3_xml.recognitionserver3.StubFormatsCollection stub
    );

    @WebMethod(operationName = "GetWorkflows", action = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml/GetWorkflows")
    @RequestWrapper(localName = "GetWorkflows", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abbyy.recognitionserver3_xml.recognitionserver3.GetWorkflows")
    @ResponseWrapper(localName = "GetWorkflowsResponse", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abbyy.recognitionserver3_xml.recognitionserver3.GetWorkflowsResponse")
    @WebResult(name = "GetWorkflowsResult", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
    public com.abbyy.recognitionserver3_xml.recognitionserver3.ArrayOfString getWorkflows(
        @WebParam(name = "serverLocation", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
        java.lang.String serverLocation
    );
}
